package session

// Identity uniquely identifies a Claude Code terminal session
type Identity struct {
	SessionID   string // UUID generated by jarvis-notify
	TTY         string // e.g., /dev/ttys001 (primary identifier for injection)
	TerminalApp string // "Terminal" or "iTerm" (determines AppleScript variant)
}

// Valid returns true if the identity has required fields
func (i Identity) Valid() bool {
	return i.SessionID != "" && i.TTY != ""
}

// TerminalType returns a normalized terminal type
func (i Identity) TerminalType() TerminalType {
	switch i.TerminalApp {
	case "iTerm.app", "iTerm", "iTerm2", "iterm", "iterm2":
		return TerminalITerm
	case "Apple_Terminal", "Terminal", "terminal":
		return TerminalApple
	default:
		return TerminalApple // Default to Terminal.app
	}
}

// TerminalType represents the type of terminal application
type TerminalType int

const (
	TerminalApple TerminalType = iota // Terminal.app
	TerminalITerm                     // iTerm2
)

func (t TerminalType) String() string {
	switch t {
	case TerminalITerm:
		return "iTerm2"
	default:
		return "Terminal.app"
	}
}
